solution
mate-academy/js_average-ages pull request #1242
Opened 2022-09-09 14:42 UTC by 1stIndominus

2022-09-10 10:23 UTC, SanyaBratashchuk requested changes

2022-09-10 10:23 UTC, SanyaBratashchuk commented on src/averageAges.js
> +    : men;
You can call filter once passing different callbacks

2022-09-10 10:23 UTC, SanyaBratashchuk commented on src/averageAges.js
> +  }, 0);
move it to the seperate function and reuse it in your main functions

2022-09-10 10:23 UTC, SanyaBratashchuk commented on src/averageAges.js
> +    : women;
The same pass different callbacks

2022-09-17 14:24 UTC, SanyaBratashchuk requested changes

2022-09-17 14:24 UTC, SanyaBratashchuk commented on src/averageAges.js
> +        const aprovCentury = Math.ceil(person.died / 100) === century;
aprovCentury? use more informative names

2022-09-17 14:24 UTC, SanyaBratashchuk commented on src/averageAges.js
> +  }, 0);
move it to the separate function and reuse it in your main functions

2022-09-17 14:24 UTC, SanyaBratashchuk commented on src/averageAges.js
> +  const averagePeopleAge = onlyWithSon
it is not an averagePeopleAge

2022-09-19 12:40 UTC, Bohdan-Maksymiuk requested changes

2022-09-19 12:40 UTC, Bohdan-Maksymiuk commented on src/averageAges.js
> +    : people;
```suggestion
  const ageDifference = onlyWithSon
    ? people.filter(child => child.sex === 'm')
    : people;
```
is it ageDifference?

2022-09-22 09:01 UTC, Bohdan-Maksymiuk approved these changes

2023-12-06 14:52 UTC, closed without merging