Solution averageAges
mate-academy/js_average-ages pull request #1246
Opened 2022-09-12 21:01 UTC by dmytronykorovych

2022-09-14 15:02 UTC, valerii-derkach requested changes

2022-09-14 15:02 UTC, valerii-derkach commented on src/averageAges.js
> +  return menAges.reduce((sum, age) => sum + age, 0) / menAges.length;
DRY you do the same calculations three times in your code, lets's create a function for these calculations

2022-09-18 08:18 UTC, SanyaBratashchuk requested changes

2022-09-18 08:18 UTC, SanyaBratashchuk commented on src/averageAges.js
> +  }
You can call filter once but pass different callbacks

2022-09-18 08:18 UTC, SanyaBratashchuk commented on src/averageAges.js
> +  }
The same pass different callbacks

2022-10-20 17:47 UTC, qoa11a approved these changes

2024-10-15 14:05 UTC, closed without merging