solution was added
mate-academy/js_average-ages pull request #1289
Opened 2022-09-21 15:06 UTC by Maksym845

2022-09-21 19:19 UTC, Yeliseiev approved these changes
Good work!

2022-09-21 19:19 UTC, Yeliseiev commented on src/averageAges.js
> +  mens = century !== false
I think you don`t need to check is century !== false and you don`t need to equalize it to 'false' in the function declaring

2022-09-22 00:23 UTC, silchyn requested changes

2022-09-22 00:23 UTC, silchyn commented on src/averageAges.js
> +  mens = century !== false
```suggestion
  mens = century
```

2022-09-22 10:56 UTC, silchyn commented on src/averageAges.js
> +  return avg;
```suggestion
  const ages = people.map(person => person.died - person.born);
  
  return agesArr.reduce((prev, person) => {
    return prev + person;
  }, 0) / agesArr.length;
```

2022-09-22 10:56 UTC, silchyn requested changes
Good job

2022-09-26 14:55 UTC, naziamoff requested changes

2022-09-26 14:55 UTC, naziamoff commented on src/averageAges.js
> +  }, 0) / ages.length;
You may do the return statement right away. And pay attention to the naming, it should perfectly describe what is stored inside
```suggestion
  const averageAge = ages.reduce((prev, person) => prev + person, 0) / ages.length;
```

2022-09-26 16:30 UTC, naziamoff requested changes
I think you should pay attention to use proper names for variables. 
Those mistakes more about English, but I highly recommend to fix them
- men instead of mens
- women instead of womens
- children instead of childrens
- average instead of avarage

2022-09-30 08:32 UTC, naziamoff approved these changes
Nice 🔥

2023-04-28 17:40 UTC, closed without merging