Solution
mate-academy/js_average-ages pull request #1446
Opened 2022-11-10 17:40 UTC by Irina-Kulish

2022-11-11 07:51 UTC, tetiana-ivanchenko requested changes

2022-11-11 07:51 UTC, tetiana-ivanchenko commented on src/averageAges.js
> +  0);
move it into separate method

2022-11-21 17:53 UTC, Irina-Kulish commented on src/averageAges.js
> +  0);
Я не до конца понимаю, что нужно изменить

2022-11-22 17:29 UTC, nazarmatsevych requested changes

2022-11-22 17:29 UTC, nazarmatsevych commented on src/averageAges.js
> +  0);
![image](https://user-images.githubusercontent.com/80700247/203381025-80e14bca-982d-45b6-a47d-5421d6c1c293.png)
![image](https://user-images.githubusercontent.com/80700247/203381084-5c662882-54cd-4a3b-9a37-a43e28f802e2.png)
![image](https://user-images.githubusercontent.com/80700247/203381649-1f284e45-f1fc-4350-a7eb-4898f8657326.png)


Ти кілька разів робиш практично одне і те ж, краще винеси цю логіку в окрему функцію і перевикористовуй її.

Якщо в тебе є якісь питання - то сміло питай в fe_chat2, так ти набагато швидше зможеш отримати відповідь, тому що на github ми зможемо відповісти тільки коли ти зробиш повторний запит на перевірку.

2023-03-21 06:38 UTC, closed without merging