solution
mate-academy/js_average-ages pull request #1483
Opened 2022-11-30 18:20 UTC by fallowlone

2022-12-01 12:31 UTC, mr-valentos approved these changes
all good)

2022-12-01 12:31 UTC, mr-valentos commented on src/averageAges.js
> +  const milfs = people.filter(milf => {
😂

2022-12-02 11:11 UTC, valerii-derkach requested changes

2022-12-02 11:11 UTC, valerii-derkach commented on src/averageAges.js
> +  return sumFilteredAges / milfs.length;
you repeat the same logic three times, so let us create a callback for these calculations

2022-12-02 11:11 UTC, valerii-derkach commented on src/averageAges.js
> +    return (onlyWithSon === true)
```suggestion
    return (onlyWithSon)
```

2022-12-02 11:11 UTC, valerii-derkach commented on src/averageAges.js
> +      : people.some(mother => mother.name === child.mother);
the same logic move to variable

2022-12-02 11:11 UTC, valerii-derkach commented on src/averageAges.js
> +    return (century !== undefined)
```suggestion
    return (!century)
```

or even better reverse condition

2022-12-02 11:11 UTC, valerii-derkach commented on src/averageAges.js
> +  const milfs = people.filter(milf => {
```suggestion
  const milfs = people.filter(milf => {
```
use meaningful names for variables, I believe if you will apply for a job in this special industry, you will have the opportunity to use such names, but now, better replace it with another

2022-12-05 09:44 UTC, ivan-kadykalo requested changes

2022-12-05 09:44 UTC, ivan-kadykalo commented on src/averageAges.js
> +  const milfsAge = mothers.map(milf => milf.died - milf.born);
Fix Valerii's comment about variables naming, such jokes will not help you to find a job.

2022-12-05 09:44 UTC, ivan-kadykalo commented on src/averageAges.js
> +    const isBoy = child.sex === 'm';
```suggestion
    const isMale = child.sex === 'm';
```

2022-12-05 10:58 UTC, solaryasha requested changes

2022-12-05 10:58 UTC, solaryasha commented on src/averageAges.js
> +  return lastValue;
```suggestion
  return averageAge(sumOfAge, filteredMen.length);
```

2022-12-05 10:58 UTC, solaryasha commented on src/averageAges.js
> +const averageAge = (array, length) => (
Why do you need to pass length as an argument? You could calculate it in the function body

2022-12-05 10:58 UTC, solaryasha commented on src/averageAges.js
> +    return (withChildren)
```suggestion
    return withChildren
```

2022-12-05 12:59 UTC, solaryasha approved these changes
👍

2022-12-05 12:59 UTC, solaryasha commented on src/averageAges.js
> +    const motherHasChild = (people.some(child => {
```suggestion
    const motherHasChild = people.some(child => {
```

2022-12-05 13:00 UTC, solaryasha commented on src/averageAges.js
> +  const sumOfAge = filteredMen.map(man => man.died - man.born);
```suggestion
  const lifeDurations = filteredMen.map(man => man.died - man.born);
```

2026-03-01 23:10 UTC, closed without merging