Solution with loops
mate-academy/js_average-ages pull request #1759
Opened 2023-02-23 07:57 UTC by Zelinskyi-Serhii

2023-02-27 11:13 UTC, andriibezkorovainyi requested changes
Great job, mate! I've found some changes I think are needed for you to don't be rejected by mentor. Fix them and you will definitely go through.

2023-02-27 11:13 UTC, andriibezkorovainyi commented on src/averageAges.js
> +  const children = people.map(person => person.name);
There is not a single man in people array who has `null` as name, you don't need this operation.

2023-03-01 10:57 UTC, andriibezkorovainyi approved these changes
GJ

2023-03-02 09:42 UTC, Andr1yK approved these changes

2023-07-12 20:05 UTC, closed without merging