solution
mate-academy/js_average-ages pull request #1770
Opened 2023-02-23 17:21 UTC by Nordexz

2023-02-28 13:41 UTC, YaroslavDzyadiv approved these changes
Good work!

2023-02-28 14:22 UTC, illiarerun requested changes

2023-02-28 14:22 UTC, illiarerun commented on src/averageAges.js
> +  }
looks confusing, in the century we can have either `number` or `array`, let's change this solution so it'd be not that confusing

2023-02-28 14:22 UTC, illiarerun commented on src/averageAges.js
> +    .reduce((sum, a) => sum + (a.died - a.born), 0) / withChild.length;
you repeat logic for calculation basically for the same array, don't do that, instead filter array either for `withChildren` or without it and perform calculations on newly created array

2023-02-28 14:22 UTC, illiarerun commented on src/averageAges.js
> +  }).filter(child => child.mothersAge !== undefined);
```suggestion
  }).filter(child => child.mothersAge);
```

2023-02-28 14:22 UTC, illiarerun commented on src/averageAges.js
> +        .find(el => typeof el === 'number'),
can you use `[0]` here?

2023-02-28 14:22 UTC, illiarerun commented on src/averageAges.js
> +        / childesWithMotherBorn.length;
you repeat yourself with theese reduce's, please find a way to avoid it

2023-03-20 20:04 UTC, sergii-nosachenko approved these changes

2023-03-20 20:04 UTC, sergii-nosachenko commented on src/averageAges.js
> +        .find(el => typeof el === 'number'),
Strange

2025-09-29 20:17 UTC, closed without merging