solution :)
mate-academy/js_average-ages pull request #1813
Opened 2023-03-03 20:08 UTC by katerynashylina

2023-03-04 10:50 UTC, SanyaBratashchuk requested changes

2023-03-04 10:50 UTC, SanyaBratashchuk commented on src/averageAges.js
> +  return averageAge;
Move this logic to the separated function and reuse it in your main functions to avoid duplication

2023-03-04 10:50 UTC, SanyaBratashchuk commented on src/averageAges.js
> +    && isMother.includes(person.name))
instead of filter with includes you can check if woman is mother via `some` method

2023-03-05 14:18 UTC, Volodymyr-Melnyk-Fron10der requested changes

2023-03-05 14:18 UTC, Volodymyr-Melnyk-Fron10der commented on src/averageAges.js
> +  const personMen = (person) => century
```suggestion
  const personMenCallback = (person) => century
```

2023-03-05 14:18 UTC, Volodymyr-Melnyk-Fron10der commented on src/averageAges.js
>  }
```suggestion
  return men.reduce(age, 0) / men.length;
}
```

2023-03-05 14:18 UTC, Volodymyr-Melnyk-Fron10der commented on src/averageAges.js
>  }
fix everywhere

2023-03-05 14:18 UTC, Volodymyr-Melnyk-Fron10der commented on src/averageAges.js
> +const age = (sum, person) => sum + (person.died - person.born);
```suggestion
const claculateAverage = people => people.reduce((sum, person) => sum + (person.died - person.born), 0) / people.length ;
```

2023-03-05 14:18 UTC, Volodymyr-Melnyk-Fron10der commented on src/averageAges.js
> +    ));
move this filter out of condition to not duplicate it

2023-03-05 14:18 UTC, Volodymyr-Melnyk-Fron10der commented on src/averageAges.js
> +  const difference = child.map(person => person.born
use destructurizing structure whenever it's possible

2023-03-05 17:03 UTC, closed without merging