Solution
mate-academy/js_average-ages pull request #1913
Opened 2023-04-01 15:41 UTC by MaksymKos

2023-04-02 08:57 UTC, etojeDenys requested changes

2023-04-02 08:57 UTC, etojeDenys commented on src/averageAges.js
> +    Math.ceil(person.died / 100) === century) : men;
```suggestion
  const men = !century 
      ? people.filter(person => person.sex === 'm')
      : people.filter(person =>  person.sex === 'm' &&
    Math.ceil(person.died / 100) === century) ;
```

2023-04-02 08:57 UTC, etojeDenys commented on src/averageAges.js
> +    );
do the same here

2023-04-02 10:57 UTC, ivadimko commented on src/averageAges.js
> +/* eslint-disable no-console */
Consider removing the eslint-disable comment and fixing the linting errors instead. 🚨

2023-04-02 10:57 UTC, ivadimko commented on src/averageAges.js
> +    .filter(person => person.mother)
Consider using a more descriptive variable name instead of `targetPeople`. For example, `mothersWithSons`. 🤔

2023-04-02 10:57 UTC, ivadimko commented on src/averageAges.js
> +    .filter(person => person.sex === 'f')
Consider using a more descriptive variable name instead of `targetPeople`. For example, `womenWithChildren`. 🤔

2023-04-03 09:18 UTC, ivadimko approved these changes
gj!

2024-10-14 06:42 UTC, closed without merging