add averageAges solution
mate-academy/js_average-ages pull request #2005
Opened 2023-05-08 20:00 UTC by DidenkoDenis306

2023-05-09 18:48 UTC, ruslanpashkov requested changes

2023-05-09 18:48 UTC, ruslanpashkov commented on src/averageAges.js
> +  return peopleAge.reduce((acc, age) => (acc + age), 0) / amountOfPeople;
what if amount === 0?

2023-05-09 18:48 UTC, ruslanpashkov commented on src/averageAges.js
> +  );
```suggestion
  const men = people.filter(person => (
    person.sex === 'm' && (century
      ? Math.ceil(person.died / 100) === century
      : true)
  ));
```

2023-05-09 18:48 UTC, ruslanpashkov commented on src/averageAges.js
> +  );
```suggestion
  const children = people.filter(person => (
    people.find(mother => mother.name === person.mother) && (onlyWithSon
      ? person.sex === 'm'
      : true)
  ));
```

2023-05-12 08:12 UTC, Anna-Tkachenko requested changes

2023-05-12 08:12 UTC, Anna-Tkachenko commented on src/averageAges.js
> +  const menAverageAge = men.map(man => man.died - man.born);
It's not `menAverageAge`, check variable name
Here is stored the set of mens` ages only

2023-05-12 08:12 UTC, Anna-Tkachenko commented on src/averageAges.js
> +  const womenAverageAge = women.map(woman => woman.died - woman.born);
Same here, check variable name

2023-05-12 08:12 UTC, Anna-Tkachenko commented on src/averageAges.js
> +function calculateAverageAge(peopleAge, amountOfPeople) {
Will be better to use `number` for count nouns
```suggestion
function calculateAverageAge(peopleAge, numberOfPeople) {
```

2023-05-12 08:12 UTC, Anna-Tkachenko commented on src/averageAges.js
> +function calculateAverageAge(peopleAge, amountOfPeople) {
Great job with moving repeated logic to separate function⭐️

2023-05-12 11:08 UTC, 33Orange approved these changes
Well done ! 👍 

All comments was fixed.

2024-07-09 10:17 UTC, closed without merging