solution
mate-academy/js_average-ages pull request #2035
Opened 2023-05-17 15:00 UTC by serentinos

2023-05-18 09:16 UTC, 33Orange requested changes
Well done!

A few moment with readability

2023-05-18 09:16 UTC, 33Orange commented on src/averageAges.js
>    // without nesting
Clean up the code from unnecessary comments.

2023-05-18 09:16 UTC, 33Orange commented on src/averageAges.js
> +    .reduce((prev, { born, died }) => prev + (died - born), 0) / mens.length
You do the same calculations with reduce in every function. Maybe we should move this calculation to a separate helper?

2023-05-18 09:16 UTC, 33Orange commented on src/averageAges.js
> +      / filteredWoman.length;
You do the same calculations with reduce in every function. Maybe we should move this calculation to a separate helper?

2023-05-18 09:16 UTC, 33Orange commented on src/averageAges.js
> +    / differences.length;
You do the same calculations with reduce in every function. Maybe we should move this calculation to a separate helper?

2023-05-18 09:16 UTC, 33Orange commented on src/averageAges.js
> +      .filter(person => person.sex === 'f');
You use a filter in both cases. Maybe it's better to do a check `withChildren` condition inside the filter?

2023-05-18 09:16 UTC, 33Orange commented on src/averageAges.js
> +        .filter(child => person.name === child.mother);
You use a filter in both cases. Maybe it's better to do a check `onlyWithSon` condition inside the filter?

2023-05-18 16:54 UTC, serentinos commented
@33Orange Thank you for all your suggestions! This advice is really helpful!

2023-05-19 12:47 UTC, 33Orange approved these changes
Well done ! 🔥

2023-08-14 11:54 UTC, closed without merging