add solution
mate-academy/js_average-ages pull request #2084
Opened 2023-05-26 12:08 UTC by dimarogkov

2023-05-29 19:32 UTC, Viktor-Kost requested changes
GJ!
Minor improvements can be applied

2023-05-29 19:32 UTC, Viktor-Kost commented on src/averageAges.js
> +    : people.filter((item) => item.sex === "m");
you can apply ternary operator inside filter method
```suggestion
  const manArr = people.filter(
    (item) => item.sex === "m" && (!century || Math.ceil(item.died / 100) === century)
  );
```

2023-05-29 19:32 UTC, Viktor-Kost commented on src/averageAges.js
> +  const womenArr = withChildren
the same with ternary

2023-05-30 08:12 UTC, OleziO approved these changes

2024-06-28 09:45 UTC, closed without merging