Solution Average-ages
mate-academy/js_average-ages pull request #2169
Opened 2023-06-20 21:16 UTC by TamaraShukalo

2023-06-21 07:36 UTC, tetiana-ivanchenko requested changes

2023-06-21 07:36 UTC, tetiana-ivanchenko commented on src/averageAges.js
> +    .filter((person) => !century || Math.ceil(person.died / 100) === century);
```suggestion
  const men = people.filter((person) => century 
    ? Math.ceil(person.died / 100) === century && person.sex === 'm'
    : person.sex === 'm'
  );
```

2023-06-21 07:36 UTC, tetiana-ivanchenko commented on src/averageAges.js
> +        .some((potentialMother) => potentialMother.mother === person.name));
combine filters

2023-06-21 07:36 UTC, tetiana-ivanchenko commented on src/averageAges.js
> +      && people
the same

2023-06-21 07:36 UTC, tetiana-ivanchenko commented on src/averageAges.js
> +  return totalWomenAge / countWomen;
move it to the separate function

2023-06-22 10:55 UTC, anstsot approved these changes
approving:sparkles:

2023-06-22 10:55 UTC, anstsot commented on src/averageAges.js
> +  );
```suggestion
  const children = people.filter(child => !!child.mother
    && (!onlyWithSon || child.sex === 'm')
    && people.some(person => person.name === child.mother)
  );
```

2024-03-25 08:28 UTC, closed without merging