solution 👩‍👧‍👧
mate-academy/js_average-ages pull request #586
Opened 2021-09-22 22:11 UTC by caelum29

2021-09-23 12:47 UTC, AVronskyi approved these changes
Interesting approach! Looks like good

2021-09-23 13:38 UTC, aliceblunt8 requested changes

2021-09-23 13:38 UTC, aliceblunt8 commented on src/averageAges.js
> +    });
let's use if, it looks more readable
```suggestion
  if (century){
    allMen = allMen.filter(({ died }) => getCentury(died) === century);
 }
```

2021-09-23 13:38 UTC, aliceblunt8 commented on src/averageAges.js
> +    : womenToCountAverageAge = allWomen;
same here, just rewrite the variable if there is withChildren

2021-09-23 13:38 UTC, aliceblunt8 commented on src/averageAges.js
> +};
so many helper functions ;0

2021-09-23 13:38 UTC, aliceblunt8 commented on src/averageAges.js
> +      });
let's first find all children and if there is onlyWithSon, we will filter only boys from all the children

2021-09-23 15:05 UTC, caelum29 commented on src/averageAges.js
> +    });
в условии задачи было что иф низзя использовать

2021-09-27 07:56 UTC, Ihor-Karpyn approved these changes

2025-10-31 11:25 UTC, closed without merging