averageAges
mate-academy/js_average-ages pull request #653
Opened 2021-11-11 18:20 UTC by voronvasia

Не зміг я правильно підібрати методи в третьому завданні, підскажіть як правильно виправити помилки. І з вимог до коду я не зрозумів чи можна використовуввати тернарний оператор, тому робив завдання з ним, бо по іншому не знаю як. Дякую за фідбек

2021-11-12 14:44 UTC, danylo-onishchuk requested changes

2021-11-12 14:44 UTC, danylo-onishchuk commented on src/averageAges.js
> +
no loop 

гитхаб не удобное место для переписки и решения вопросов 

если тебе нужна помощь - пиши в слэк

2021-11-15 14:00 UTC, vkryvytskyy requested changes

2021-11-15 14:00 UTC, vkryvytskyy commented on src/averageAges.js
> +  const averageYear = century ? averageAgeMenCentury : averageAgeMen;
Зачем делать два reduce, чтобы потом возвращать значение только одного из них? 
Делай проверку в самом начале
```javascript
  const men = people.filter(person =>
    century
      ? person.sex === 'm' && Math.ceil(person.died / 100) === century
      : person.sex === 'm');

  return men.reduce((sum, y) => sum + (y.died - y.born), 0) / men.length;
```
Остальные функции можно сделать по тому же принципу

2021-11-16 15:38 UTC, danylo-onishchuk approved these changes

2023-12-09 20:10 UTC, closed without merging