Solution
mate-academy/js_average-ages pull request #684
Opened 2021-11-18 16:12 UTC by Veronika-Korona

2021-11-18 19:27 UTC, Nadiyahr approved these changes
Great.

2021-11-19 09:06 UTC, aionova requested changes
let's try to add more logic to the styling of your code

2021-11-19 09:06 UTC, aionova commented on src/averageAges.js
> +    mother.name === person.mother);
```suggestion
  const womanWithChildren = people.some(person => (
    mother.name === person.mother
  ));
```

2021-11-19 09:06 UTC, aionova commented on src/averageAges.js
> +
```suggestion
  const women = people.filter(person => (
    withChildren
      ? person.sex === 'f'
        && calculateWomanWithChildren(people, person)
      : person.sex === 'f'
  ));

```

2021-11-19 09:06 UTC, aionova commented on src/averageAges.js
> +  0) / children.length;
```suggestion
  return children.reduce((sum, child) => (
    sum + ((child.born - people.find(mother => (
      mother.name === child.mother
    )).born
  ))), 0) / children.length;
```

2021-11-19 15:24 UTC, aionova approved these changes
GJ!

2025-01-07 19:21 UTC, closed without merging