this code is gonna be so fun to read
mate-academy/js_average-ages pull request #769
Opened 2022-01-24 17:16 UTC by trtskvalerie

2022-01-25 15:08 UTC, tvoyammn requested changes
нубік реджектнув про

2022-01-25 15:08 UTC, tvoyammn commented on src/averageAges.js
> +  const ages = men.map(person => person.died - person.born);
лишня змінна, ти можеш зразу редусити масив `men`

2022-01-25 15:08 UTC, tvoyammn commented on src/averageAges.js
> +function calculateWomenAverageAge(people, withChildren = false) {
зочєм `withChildren = false`???

2022-01-25 15:08 UTC, tvoyammn commented on src/averageAges.js
> +    .map(person => person.mother);
можна було і обойтись.... але єслі сільно хочеца...

2022-01-25 15:08 UTC, tvoyammn commented on src/averageAges.js
> +  const ages = women.map(person => person.died - person.born);
опять лішнє, зарідюсь `women` зразу

2022-01-25 15:08 UTC, tvoyammn commented on src/averageAges.js
> +function calculateAverageAgeDiff(people, onlyWithSon = false) {
те саме, нашо `false` по дефолту, єслі не передадуть буде андефайнд просто, он так же даст `false` на провєркє

2022-01-25 15:08 UTC, tvoyammn commented on src/averageAges.js
> +    ));
хммммм, а зачєм тобі `map`, якій нічьо не ретурнить??????????

2022-01-25 15:25 UTC, trtskvalerie commented on src/averageAges.js
> +function calculateWomenAverageAge(people, withChildren = false) {
>:((((((((

2022-01-25 15:38 UTC, tvoyammn approved these changes
раз уж так просиш

2022-01-25 16:10 UTC, OleksiiBlezniuk approved these changes

2022-01-25 16:10 UTC, OleksiiBlezniuk commented on src/averageAges.js
> +function calculateWomenAverageAge(people, withChildren = false) {
Значение по умолчанию - лишнее

2022-01-25 16:10 UTC, OleksiiBlezniuk commented on src/averageAges.js
> +function calculateAverageAgeDiff(people, onlyWithSon = false) {
Значение по умолчанию - лишнее

2022-01-25 16:10 UTC, OleksiiBlezniuk commented on src/averageAges.js
> +      )).born
```suggestion
    .map(child => (child.born - mothers
      .find(person => (person.name === child.mother)
    ).born
```

2024-03-17 12:18 UTC, closed without merging

2024-03-17 12:20 UTC, tvoyammn commented
Why closed? Add explanation