solution for #averageAges
mate-academy/js_average-ages pull request #813
Opened 2022-02-15 12:28 UTC by jstmpelowycz

2022-02-15 12:49 UTC, SanyaBratashchuk approved these changes
good readable code. good job

2022-02-15 13:13 UTC, solaryasha requested changes

2022-02-15 13:13 UTC, solaryasha commented on src/averageAges.js
> +  if (century) {
Let's practice ternary and logical operators
```
replace `if ()` statement with &&, || or ?:

2022-02-15 13:13 UTC, solaryasha commented on src/averageAges.js
> +  if (withChildren) { // O(N^2) :(
Use hash map for avoiding n**2 complexity

You can implement hash map with `reduce` and `{}` as initial value

2022-02-15 13:13 UTC, solaryasha commented on src/averageAges.js
> +  if (withChildren) { // O(N^2) :(
It's not required, but it will be good practice for you.

2022-02-15 17:51 UTC, solaryasha approved these changes

2022-02-16 10:06 UTC, jstmpelowycz commented on src/averageAges.js
> +  if (withChildren) { // O(N^2) :(
```s

2022-02-16 10:06 UTC, jstmpelowycz commented on src/averageAges.js
> +  if (withChildren) { // O(N^2) :(
''фф''

2022-02-16 10:06 UTC, jstmpelowycz commented on src/averageAges.js
> +  if (withChildren) { // O(N^2) :(
*и*

2023-03-13 08:15 UTC, closed without merging