solution
mate-academy/js_average-ages pull request #918
Opened 2022-05-03 14:23 UTC by ZUBOV-ILLIA

2022-05-05 16:31 UTC, SavMary approved these changes
check the names of variables: mans, womens, chields - are wrong

2022-05-05 16:31 UTC, SavMary commented on src/averageAges.js
> +    return people.some(y => y.name === x.mother);
You should use more semantic variables than x and y for better understanding

2022-05-05 16:40 UTC, Anna-Tkachenko requested changes

2022-05-06 14:06 UTC, Anna-Tkachenko approved these changes
⭐️

2025-03-11 09:28 UTC, closed without merging