Average ages
mate-academy/js_average-ages pull request #997
Opened 2022-06-10 12:37 UTC by vsupruniuk

2022-06-10 13:30 UTC, jstmpelowycz requested changes

2022-06-13 10:48 UTC, vsupruniuk commented
I will try to fix the problem of time complexity when I finish the course of algorithms and data structures

2022-06-13 11:59 UTC, Olexandr6 requested changes
Almost done

2022-06-13 11:59 UTC, Olexandr6 commented on src/averageAges.js
> +  const menInCentry = century
It's not `menInCentry` in cause `century` === `undefined`

2022-06-13 11:59 UTC, Olexandr6 commented on src/averageAges.js
> +    : men;
You filter 2 times when there is `century`. Let's implement this using only one filter

2022-06-13 11:59 UTC, Olexandr6 commented on src/averageAges.js
> +
The same case here, let's use filter only once

2022-06-13 11:59 UTC, Olexandr6 commented on src/averageAges.js
> +    .filter(children => people.some(person => children.mother === person.name));
HashMap is crying🥲

2022-06-13 11:59 UTC, Olexandr6 commented on src/averageAges.js
> +    : child;
Let's use filtering once🥲

2022-06-13 11:59 UTC, Olexandr6 commented on src/averageAges.js
> +  const childIsSon = onlyWithSon
It's not always sons here. Pay attention to variables naming
```suggestion
  const childIsSon = onlyWithSon
```

2022-06-13 14:22 UTC, Olexandr6 approved these changes

2024-01-14 13:43 UTC, closed without merging